CODES =
  METHOD_NOT_FOUND: -32601
  INVALID_ORIGIN: 100
  DEFAULT: -1

MESSAGES = {}
MESSAGES[CODES.METHOD_NOT_FOUND] = 'Method not found'
MESSAGES[CODES.INVALID_ORIGIN] = 'Invalid origin'
MESSAGES[CODES.DEFAULT] = 'Error'

module.exports = {CODES, MESSAGES}
